name: Circuitikz Compilation

on:
  workflow_dispatch:
    inputs:
      circuit_code:
        description: 'Il codice Circuitikz da compilare'
        required: true
        default: '\\draw (0,0) to [R, l=\\$R_1\\$] (2,0);'

jobs:
  compile_circuit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup LaTeX environment and install tools
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-latex-base texlive-pictures texlive-fonts-recommended texlive-fonts-extra texlive-science poppler-utils

      - name: Create LaTeX file
        run: |
          echo "\documentclass[tikz,border=10pt]{standalone}" > circuit.tex
          echo "\usepackage{circuitikz}" >> circuit.tex
          echo "\begin{document}" >> circuit.tex
          echo "\begin{tikzpicture}" >> circuit.tex
          echo "${{ github.event.inputs.circuit_code }}" >> circuit.tex
          echo "\end{tikzpicture}" >> circuit.tex
          echo "\end{document}" >> circuit.tex

      - name: Compile LaTeX file
        run: |
          pdflatex -interaction=nonstopmode circuit.tex

      - name: Convert PDF to PNG
        run: |
          pdftoppm -png -r 300 circuit.pdf circuit

      - name: Upload PNG as artifact
        uses: actions/upload-artifact@v3
        with:
          name: circuit-image
          path: circuit-1.png
